//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoppingx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public Categoria()
        {
            this.Subcategorias = new HashSet<Subcategoria>();
        }
    
        public int CategoriaId { get; set; }
        public string Nome { get; set; }
        public Nullable<int> lomadeeId { get; set; }
    
        public virtual ICollection<Subcategoria> Subcategorias { get; set; }
    }
}
