//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoppingx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loja
    {
        public Loja()
        {
            this.Precoes = new HashSet<Preco>();
        }
    
        public int LojaId { get; set; }
        public Nullable<int> LomadeeId { get; set; }
        public string Nome { get; set; }
        public string Logo { get; set; }
        public Nullable<decimal> Avaliacao { get; set; }
    
        public virtual ICollection<Preco> Precoes { get; set; }
    }
}
