//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoppingx.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shoppingxEntities : DbContext
    {
        public shoppingxEntities()
            : base("name=shoppingxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categoria> Categorias { get; set; }
        public DbSet<Loja> Lojas { get; set; }
        public DbSet<Preco> Precoes { get; set; }
        public DbSet<Produto> Produtoes { get; set; }
        public DbSet<Subcategoria> Subcategorias { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
    }
}
