//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoppingx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preco
    {
        public int PrecoId { get; set; }
        public Nullable<int> ProdutoId { get; set; }
        public Nullable<int> LojaId { get; set; }
        public Nullable<int> Preco1 { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    
        public virtual Loja Loja { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
