//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoppingx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public Produto()
        {
            this.Precoes = new HashSet<Preco>();
            this.Usuprods = new HashSet<Usuprod>();
        }
    
        public int ProdutoId { get; set; }
        public Nullable<int> LomadeeId { get; set; }
        public string Nome { get; set; }
        public Nullable<int> Clicks { get; set; }
        public Nullable<int> Compras { get; set; }
        public Nullable<decimal> Receita { get; set; }
        public Nullable<int> SubcategoriaId { get; set; }
    
        public virtual ICollection<Preco> Precoes { get; set; }
        public virtual Subcategoria Subcategoria { get; set; }
        public virtual ICollection<Usuprod> Usuprods { get; set; }
    }
}
