//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoppingx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcategoria
    {
        public Subcategoria()
        {
            this.Produtoes = new HashSet<Produto>();
        }
    
        public int SubcategoriaId { get; set; }
        public Nullable<int> CategoriaId { get; set; }
        public string Nome { get; set; }
        public Nullable<int> LomadeeId { get; set; }
        public string Descricao { get; set; }
        public string Tags { get; set; }
        public string Imagem { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual ICollection<Produto> Produtoes { get; set; }
    }
}
